// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIDudfp61AySM7H5MJnZ9N4Lt4T1bImZQ',
    appId: '1:726774231210:web:1fff13eaab1cc1e736e0d3',
    messagingSenderId: '726774231210',
    projectId: 'fir-project-17558',
    authDomain: 'fir-project-17558.firebaseapp.com',
    storageBucket: 'fir-project-17558.appspot.com',
    measurementId: 'G-JZ3H04FB51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuO8I9iz75F7zxrM_0Ol8EgWoywP9EltI',
    appId: '1:726774231210:android:19288c5c7bcdd68536e0d3',
    messagingSenderId: '726774231210',
    projectId: 'fir-project-17558',
    storageBucket: 'fir-project-17558.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBTscABns4K9e-wSblXvCFng0utM-sPU0',
    appId: '1:726774231210:ios:111148dd987d68c436e0d3',
    messagingSenderId: '726774231210',
    projectId: 'fir-project-17558',
    storageBucket: 'fir-project-17558.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBTscABns4K9e-wSblXvCFng0utM-sPU0',
    appId: '1:726774231210:ios:6bfe94a3d8a14f7b36e0d3',
    messagingSenderId: '726774231210',
    projectId: 'fir-project-17558',
    storageBucket: 'fir-project-17558.appspot.com',
    iosBundleId: 'com.example.firebaseProject.RunnerTests',
  );
}
